# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cancer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARxING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(251, 237, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.titleLabel = QtWidgets.QLabel(self.centralwidget)
        self.titleLabel.setGeometry(QtCore.QRect(210, 20, 550, 40))

        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.titleLabel.setFont(font)
        self.titleLabel.setStyleSheet("color: rgb(74, 98, 138)\n"
"\n"
"")
        self.titleLabel.setScaledContents(False)
        self.titleLabel.setWordWrap(False)
        self.titleLabel.setObjectName("titleLabel")
        self.input_image_button = QtWidgets.QPushButton(self.centralwidget)
        self.input_image_button.setGeometry(QtCore.QRect(40, 120, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.input_image_button.setFont(font)
        self.input_image_button.setStyleSheet("background-color:rgb(74, 98, 138);\n"
"color: rgb(255, 255, 255);")
        self.input_image_button.setObjectName("input_image_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 80, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(74, 98, 138)\n"
"\n"
"")
        self.label.setObjectName("label")
        self.processing_button = QtWidgets.QPushButton(self.centralwidget)
        self.processing_button.setGeometry(QtCore.QRect(40, 200, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.processing_button.setFont(font)
        self.processing_button.setStyleSheet("background-color:rgb(74, 98, 138);\n"
"color: rgb(255, 255, 255);")
        self.processing_button.setObjectName("processing_button")
        self.reset_button = QtWidgets.QPushButton(self.centralwidget)
        self.reset_button.setGeometry(QtCore.QRect(40, 280, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.reset_button.setFont(font)
        self.reset_button.setStyleSheet("background-color:rgb(74, 98, 138);\n"
"color: rgb(255, 255, 255);")
        self.reset_button.setObjectName("reset_button")
        self.exit_button = QtWidgets.QPushButton(self.centralwidget)
        self.exit_button.setGeometry(QtCore.QRect(40, 440, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.exit_button.setFont(font)
        self.exit_button.setStyleSheet("background-color:rgb(74, 98, 138);\n"
"color: rgb(255, 255, 255);")
        self.exit_button.setObjectName("exit_button")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(270, 520, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift SemiBold")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(260, 90, 481, 411))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(74, 98, 138);\n"
"border-radius: 10px\n"
"\n"
"")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label1 = QtWidgets.QLabel(self.groupBox)
        self.label1.setGeometry(QtCore.QRect(190, 370, 180, 30))

        font = QtGui.QFont()
        font.setPointSize(12)
        self.label1.setFont(font)
        self.label1.setStyleSheet("color: rgb(255, 255, 255);")
        self.label1.setObjectName("label1")
        self.input_image_label = QtWidgets.QLabel(self.groupBox)
        self.input_image_label.setGeometry(QtCore.QRect(50, 30, 391, 331))
        self.input_image_label.setStyleSheet("border: 2px solid #333;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.input_image_label.setText("")
        self.input_image_label.setObjectName("input_image_label")
        self.result_label = QtWidgets.QLabel(self.centralwidget)
        self.result_label.setGeometry(QtCore.QRect(360, 520, 371, 31))
        self.result_label.setStyleSheet("border: 2px solid #333;\n"
"background-color: rgb(255, 255, 255);\n"
"border-radius: 5px;")
        self.result_label.setText("")
        self.result_label.setObjectName("result_label")
        self.symptom_button = QtWidgets.QPushButton(self.centralwidget)
        self.symptom_button.setGeometry(QtCore.QRect(40, 360, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.symptom_button.setFont(font)
        self.symptom_button.setStyleSheet("background-color:rgb(74, 98, 138);\n"
"color: rgb(255, 255, 255);")
        self.symptom_button.setObjectName("symptom_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "NHẬP HÌNH ẢNH X-QUANG"))
        self.input_image_button.setText(_translate("MainWindow", "Ảnh đầu vào"))
        self.label.setText(_translate("MainWindow", "Menu"))
        self.processing_button.setText(_translate("MainWindow", "Tiến hành"))
        self.reset_button.setText(_translate("MainWindow", "Làm mới"))
        self.exit_button.setText(_translate("MainWindow", "Thoát"))
        self.label_6.setText(_translate("MainWindow", "Kết quả"))
        self.label1.setText(_translate("MainWindow", "Ảnh đầu vào"))
        self.symptom_button.setText(_translate("MainWindow", "Triệu chứng"))
